name: Pylint Code Checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  code_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pylint

      - name: Run Pylint
        run: pylint .
